### PR TITLE
edit genid shebang

### PR DESCRIPTION
**Pull request by skovranek**
resolves https://github.com/bootdotdev/courses/issues/5822

### CODE REVIEW

**Comment by cgsdev0** [comment]
I think this change will break this exercise:

https://github.com/bootdotdev/courses/blob/2808f6bcee7cf8f7a4d4dfb2728fa2452d1b6805/courses/learn-shells-and-terminals/4-programs/exercises/2-shebang/text_input.yml#L2

this is a little tricky because people working on the course may already have the `worldbanc.zip` downloaded, and so they wont get the updated version.

we can try to figure this out together tomorrow 🤔

**Comment by cgsdev0** [comment]
ok wait i thought about this more

what if we just update the exercise to accept either one as the right answer?

probably good enough 👍

**Comment by skovranek** [comment]
To which exercise do you refer?

I'd imagine we should 1) merge this PR if it contains the appropriate correction, and 2) change 3.4 and 4.2 to accept answers for both repo versions. After some time, we can reasonably assume the people with the older repo version will have completed the shells course and we can remove the dual solutions.

I checked, it's about 120 users who started the course with the latest repo and still need to finish it.

It's up to you.

**Review by cgsdev0 — APPROVED** [review]
yep, i agree

let's just try to land both changes ~roughly the same time and it should be good 👍

**Pull request merged**
